development:
  adapter: async

test:
  adapter: test

production:
  adapter: <%= ENV['REDIS_URL'].present? ? 'redis' : 'async' %>
  <% if ENV['REDIS_URL'].present? %>
  url: <%= ENV.fetch("REDIS_URL") %>
  channel_prefix: kohai_game_web3_production
  <% end %>
